language: node_js
node_js:
- '7'
env:
  global:
    secure: rYA8PbLeesJPRnj5X1QC1oNPrq2hFTXdte1TAS7DwZy/j3w7LprUxwDjH1RYhKAEZbsxPkEcM0dYQZJYebz3LFejXt0Qmv1VUm4st5xZv8Hp09BRjU0gzQkESHZWSiHpb7KpeUPitlWtPwJBPXk941hByAWIVboEico4pT5HipD+ceSV6JJN9/p5B9hNsL0FJDt0GMgcEcUXHDrJ+HZnsDi9rR5YSc02wSW6Qcy69Q4wy+sAQJC1nKl+we76r1UeOkqlK0Q1mM2cRtgUX/nwo511nn+L2KqU+Xy6FHsVjtehT4jpr0ki9iTtGIqaULmedi3zJ/u2VZMUyjwqr/EqJpWZpnQNjwVEuAraS5RNDl0tgwaLq6bsnblLEX6z1AoArZ6SVlGLaGClRtaG5bNCLjDSRANZ5s0EkiG/++SMcIHigqJcUUJZ9dz8Eanur66UaZpUc8cyf3mdwdy/7wNvRIF078rjHz4HYVtIE56rxzKx/6kNsF6Tu7r7EfObNN6frKAhYGvCP9ax5eV9qnlltTRkB24aa6y6VneCBv9GZ0bamAYlPrKyLYNDeB049BEfzirkBBf+zc3OOw/huJMfocrxq1tvzy3JAPnaZGLjqQjyEdBu8I0YA3Jy7SM9mQkhbBGI4cmjikNzFIgGGuWFfzQWpUvRRLCJsK1PAEqdjPo=
